-- clear-lessons.sql — FULL PURGE of all lesson data.
--
-- Destructive and irreversible. Run explicitly against the target database:
--   ssh spruce-cedar.exe.xyz 'set -a; . /home/exedev/nihongo-practice/.env; set +a; \
--     psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f -' < scripts/clear-lessons.sql
--
-- Deletes:
--   1. Every `items` row generated by a lesson (tagged `lesson:<id>`). This
--      cascades to that item's `reviews` and `review_state` rows (SRS history).
--   2. Every `lessons` row, which cascades to `lesson_items`, `lesson_state`,
--      and `lesson_sections`.
-- Deleting `lessons` does NOT cascade into `items`, so the tag-based item
-- delete (step 1) is required to avoid leaving orphaned lesson cards in the
-- shared review pool.

BEGIN;

DELETE FROM items
  WHERE EXISTS (SELECT 1 FROM unnest(tags) AS t WHERE t LIKE 'lesson:%');

DELETE FROM lessons;

COMMIT;
